- name: Playbook
  hosts: ACI_AutoPods_lab
  connection: local
  gather_facts: no

  tasks:
    - name: Add a new Tenant
      aci_tenant:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: no
        tenant: hecserra2
        description: hecserra Ansible
        state: present