---

- name: Ansible Playbook demo1
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: ios

  vars:
    StaticRoutes:
    - route: 192.168.1.0
      mask: 255.255.255.0
      next_hop: 10.0.0.1
    - route: 192.168.2.0
      mask: 255.255.255.0
      next_hop: 10.0.0.1

  tasks:

  - name: Get config for IOS devices
    cisco.ios.ios_facts:
      gather_subset: all

  - name: Display all facts
    debug:
      msg: "{{ ansible_facts }}"

  - name: Display specific info
    debug:
      msg: "The hostname is {{ ansible_net_hostname }} and the version is {{ ansible_net_version }}"

  - name: Display interfaces info
    debug:
      msg: "{{ ansible_facts.net_interfaces }}"

  - name: Display interfaces info
    debug:
      msg: "{{ ansible_net_interfaces }}" 

  - name: Creating an empty file
    file:
      path: output.txt
      state: touch

  - name: copy to file
    lineinfile:
      dest: output.txt
      line: "The hostname is {{ ansible_net_hostname }} and the version is {{ ansible_net_version }}"
    with_items:
      "{{ ansible_facts }}"

  - name: render a Jinja2 template onto an IOS device
    cisco.ios.ios_config:
      backup: yes
      src: ios_template.j2