---

- name: Ansible Playbook demo1
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: n9k

  vars:
    ansible_command_timeout: 3600


  tasks:

    - name: Get config for NX-OS devices
      cisco.nxos.nxos_facts:
        gather_subset: all

    - name: Display all info
      debug:
        msg: "{{ ansible_facts }}"


    - name: Display specific info
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the version is {{ ansible_net_version }}"
