- name: Merge provided configuration with device configuration
  cisco.iosxr.iosxr_l3_interfaces:
     config:
     - name: Loopback101
       ipv4:
       - address: 10.101.101.101/32
     - name: Loopback102
       ipv4:
       - address: 10.102.102.102/32
     state: merged
